# Generated by Django 5.2.4 on 2025-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_client_clinician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
